version: '3'
services:
    nginx:
        restart: always
        image: yoon7548/docker-nginx-campfire
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - backend

    backend:
        image: yoon7548/docker-backend-campfire
        container_name: app_backend
        volumes:
            - /app/node_modules
            - ./backend:/app
        mem_limit: 128m
        environment:
            PORT: $PORT
            MYSQL_HOST: $MYSQL_HOST
            MYSQL_USERNAME: $MYSQL_USERNAME
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_PORT: $MYSQL_PORT
            S3_ACCESS_KEY_ID: $S3_ACCESS_KEY_ID
            S3_SECRET_ACCESS_KEY: $S3_SECRET_ACCESS_KEY
            PROFILEIMG_BUCKETNAME: $PROFILEIMG_BUCKETNAME
            POSTIMG_BUCKETNAME: $POSTIMG_BUCKETNAME
            CRYPTO_SECRET_KEY: $CRYPTO_SECRET_KEY
            TOKEN_USER_SECRET_KEY: $TOKEN_USER_SECRET_KEY
            TOKEN_HOST_SECRET_KEY: $TOKEN_HOST_SECRET_KEY
            KAKAO_CLIENT_ID: $KAKAO_CLIENT_ID
            KAKAO_REDIRECT_URI: $KAKAO_REDIRECT_URI
            NAVER_CLIENT_ID: $NAVER_CLIENT_ID
            NAVER_SECRET: $NAVER_SECRET
            GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
            GOOGLE_REDIRECT_URI: $GOOGLE_REDIRECT_URI
            GOOGLE_SECRET: $GOOGLE_SECRET
            SMS_API_KEY: $SMS_API_KEY
            SMS_ACCESS_KEY: $SMS_ACCESS_KEY
            SMS_SECRET_KEY: $SMS_SECRET_KEY
